### PR TITLE
fix : Inconsistent Go Back button behavior on theme page

### PR DESCRIPTION
**Pull request by adityayaduvanshi**
## Changes Made
1. Refactored `ThemePage` component to receive data as props instead of fetching client-side.
2. Updated `ThemeInfoPage` to fetch theme data server-side and pass it to `ThemePage`.
3. Improved error handling for cases where a theme is not found.
4. Enhanced the UI for the "Theme not found" scenario.

## Why These Changes?
- Improves performance by leveraging server-side rendering for data fetching.
- Enhances SEO by ensuring content is available on initial page load.
- Provides a better user experience with a more informative and visually appealing error state.
- Aligns with Next.js best practices for data fetching in server components.

## Testing
- Verified that themes load correctly when found.
- Confirmed that the "Theme not found" UI displays appropriately for non-existent themes.
- Ensured that all interactive elements (e.g., "Go back" button) work as expected.

### CODE REVIEW

**Comment by mauro-balades** [comment]
This has been changed

**Comment by adityayaduvanshi** [comment]
Can i know the issue with my pull request?

**Comment by adityayaduvanshi** [comment]
@mauro-balades can i know the issue with my pull request?

**Comment by mauro-balades** [comment]
I've changed the site to be a static website, this PR is simply outdated, im very sorry

**Comment by adityayaduvanshi** [comment]
@mauro-balades okayy no problem.

**Pull request closed without merging**
