### PR TITLE
Fixed-#220

### PR DESCRIPTION
**Pull request by ZhenyaGoroh**
image

If the text is not correct, suggest another one, I'll change

### CODE REVIEW

**Comment by LeMoonStar** [comment]
If I understand correctly, this only adds a notice after selecting and Downloading Flatpak (I am currently not able to test this myself). This will probably not be noticed by the users.

Instead, the Flatpak option should be marked - for example with a red border and being slightly opaque and show a very clear warning when selected.

**Comment by ZhenyaGoroh** [comment]
> If I understand correctly, this only adds a notice after selecting and Downloading Flatpak (I am currently not able to test this myself). This will probably not be noticed by the users.
> 
> Instead, the Flatpak option should be marked - for example with a red border and being slightly opaque and show a very clear warning when selected.

Yeah, it just adds this notice. There is no implemented components for warning text so Cheff or Canoa need to review this. If they agree with your suggestion, I can implement it then.

**Comment by mauro-balades** [comment]
Great!

**Comment by LeMoonStar** [comment]
I honestly don't believe this notice is obvious enough. It only appears AFTER the flatpakref was downloaded, and is likely not even read by most users as it appears like a "thank you" message.

For Context, this is what the user sees:
image

**Pull request merged**
