### PR TITLE
Clipboard copy button

### PR DESCRIPTION
**Pull request by ZhenyaGoroh**
I suggest adding a 'Copy to Clipboard' button for scripts. Additionally, I would like to implement a toast notification upon copying, but I am unsure if there are any existing designs for it. Another enhancement I propose is adding a script for Flatpak installation similar to the one you have for AppImage installation. If you approve of these suggestions, I can implement them in this PR.

image

After copy button click check icon is shown for 3 sec

image

### CODE REVIEW

**Comment by ZhenyaGoroh** [comment]
I can show this icon when you copied to clipboard instead of toast
image

**Comment by NOCanoa** [comment]
btw are u in discord?

**Comment by ZhenyaGoroh** [comment]
> btw are u in discord?

Yes, I joined zen server

**Comment by mauro-balades** [comment]
Thanks a lot!

**Pull request merged**
