### PR TITLE
fix typo and grammar in features.tsx

### PR DESCRIPTION
**Pull request by zahyaah**
# Issue #46
## Description
This PR addresses a typo and grammar issue in `features.tsx`. The changes are reflected in the updated screenshots below.

## Before: 
Screenshot 2024-08-23 at 1 54 15 AM  Screenshot 2024-08-23 at 1 55 57 AM

## After: 
Screenshot 2024-08-23 at 2 30 37 AM  Screenshot 2024-08-23 at 2 31 43 AM

### CODE REVIEW

**Comment by ChildishhAlbino** [comment]
Noticed this myself and happy to see someone has fixed it. Nice catch @zahyaah.

Hopefully someone from the core team authorizes soon.

**Comment by zahyaah** [comment]
> Noticed this myself and happy to see someone has fixed it. Nice catch @zahyaah.
> 
> Hopefully someone from the core team authorizes soon.

thanks @ChildishhAlbino :) fingers crossed that the core team approves the PR soon

**Comment by Alex-Costea** [comment]
This is the first thing I notice on the front page, hopefully it can be merged soon as really makes the site feel unprofessional

**Comment by Alex-Costea** [comment]
Also, maybe "Goodbye bad performance" should be "Goodbye, bad performance!" or something to that effect

**Review by NOCanoa — APPROVED** [review]

**Pull request merged**
