### PR TITLE
Fixed #188

### LINKED ISSUE #188: It's not possible to navigate from the home page with javascript disabled
All the "links" are buttons with javascript that perform the navigation actions, and if javascript is disabled for any number of reasons then none of those buttons work.

imagen

### PR DESCRIPTION
**Pull request by ZhenyaGoroh**
Changed buttons to links so they work when JS is disabled.

### CODE REVIEW

**Comment by ZhenyaGoroh** [comment]
If my solution is acceptable, I can check that all links work when JavaScript is disabled.

**Comment by mauro-balades** [comment]
THanks! But can we move them to "a" tags instead of `Link`?

**Comment by JosueGalRe** [comment]
> THanks! But can we move them to "a" tags instead of `Link`?

Not really, if you're using Next you should use Link to internal URLs, this way the framework handles the redirections correctly.

**Comment by ZhenyaGoroh** [comment]
> THanks! But can we move them to "a" tags instead of `Link`?

Next has Link tag for navigating within the app, so it's a good practice to use Link where it is possible.

**Comment by mauro-balades** [comment]
It uses pre-fetching, which I dont like

**Comment by JosueGalRe** [comment]
> It uses pre-fetching, which I dont like/need
Then I think using `prefetch={false}` should do the trick @ZhenyaGoroh

**Comment by ZhenyaGoroh** [comment]
Yeah, I can do like this
`
<Link href="/dashboard" prefetch={false}>
      Dashboard
</Link>
`

**Comment by ZhenyaGoroh** [comment]
> > It uses pre-fetching, which I dont like/need
> 
> Then I think using `prefetch={false}` should do the trick @ZhenyaGoroh

Yeah, I can add prefetch={false} to Link tags

**Comment by mauro-balades** [comment]
Thanks!

**Pull request merged**
