### PR TITLE
Flatpak warning

### PR DESCRIPTION
**Pull request by ZhenyaGoroh**
image
As white text is not really noticeable, I changed it to yellow

### CODE REVIEW

**Comment by LeMoonStar** [comment]
I still want to note, just as in https://github.com/zen-browser/www/pull/224#issuecomment-2402998885: The warning should appear BEFORE a user downloads the flatpak. This appears AFTER the user downloaded it - In most cases the user is not looking at this page. Information on this page should never be critical information.
Critical information should be shown on the site the user chooses the download option on. That is, once the user clicks on the Flatpak choice - NOT after they clicked "download".

**Comment by LeMoonStar** [comment]
This is therefor not a real improvement over #224 - and still not what I had in mind as a solution to #220

**Comment by ZhenyaGoroh** [comment]
I can show modal when u click on flatpak, what do u think?

**Comment by ZhenyaGoroh** [comment]
> > I can show modal when u click on flatpak, what do u think?
> 
> What exactly would that look like?

Modal window with this yellow warning text and 2 buttons, download anyway and back
Stm like this for example

**Comment by LeMoonStar** [comment]
> > > I can show modal when u click on flatpak, what do u think?
> > 
> > 
> > What exactly would that look like?
> 
> Modal window with this yellow warning text and 2 buttons, download anyway and back Stm like this for example

That sounds like a good solution to make sure the user actually understands and knows before installing Zen.

**Comment by ZhenyaGoroh** [comment]
@LeMoonStar this is already implemented in the lib we use in this project
image

**Comment by LeMoonStar** [comment]
> @LeMoonStar this is already implemented in the lib we use in this project image

Yes! I think something like that would be perfect - probably with better colors tho :P

Obviously the actual maintainers of this should have the say in what all this should work and look like.
But I personally highly recommend informing the user like this.

**Comment by ZhenyaGoroh** [comment]
> > @LeMoonStar this is already implemented in the lib we use in this project image
> 
> Yes! I think something like that would be perfect - probably with better colors tho :P
> 
> Obviously the actual maintainers of this should have the say in what all this should work and look like. But I personally highly recommend informing the user like this.

Canoa agreed with this solution

**Comment by ZhenyaGoroh** [comment]
image
Like this

**Comment by ZhenyaGoroh** [comment]
This modal opens only when u selected optimized and clicked download, if u click cancel, the modal closes and u still on this page, if u click download, u get redirected to download page and auto download starts

**Comment by NOCanoa** [comment]
@ZhenyaGoroh should it say somting like u can intall generic version?

**Comment by ZhenyaGoroh** [comment]
> @ZhenyaGoroh should it say somting like u can intall generic version?

I don't really know what text should be here, maybe @LeMoonStar will suggest or cheff

**Comment by LeMoonStar** [comment]
> > @ZhenyaGoroh should it say somting like u can intall generic version?
> 
> I don't really know what text should be here, maybe @LeMoonStar will suggest or cheff

I think the current text is quite good already.

My attempt: "The Flatpak doesn't provide the optimized version of Zen. If you don't want to miss out on performance, please choose another method."

**Comment by LeMoonStar** [comment]
The Button should probably say "Download anyway" instead of just "Download".

**Comment by ZhenyaGoroh** [comment]
> The Button should probably say "Download anyway" instead of just "Download".

I'll fix tomorrow

**Comment by ZhenyaGoroh** [comment]
image

**Comment by LeMoonStar** [comment]
As discussed on discord just now - Labeling the button "Download Generic Instead" might be clearer.

**Comment by ZhenyaGoroh** [comment]
> As discussed on discord just now - Labeling the button "Download Generic Instead" might be clearer.

Change Download anyway to Download Generic Instead?
Wont it mislead user that he'll be redirected to generic download page?

**Comment by NOCanoa** [comment]
> > As discussed on discord just now - Labeling the button "Download Generic Instead" might be clearer.
> 
> Change Download anyway to Download Generic Instead?
> Wont it mislead user that he'll be redirected to generic download page?

isnt it suposed to redirect to generic flatpak download page?

**Comment by KiKaraage** [comment]
**Flatpak will install the Generic version!** Please select other formats if you want to install the Optimized version.

and the button will be **Download Generic anyway**

**Comment by ZhenyaGoroh** [comment]
> > > As discussed on discord just now - Labeling the button "Download Generic Instead" might be clearer.
> > 
> > Change Download anyway to Download Generic Instead?
> > Wont it mislead user that he'll be redirected to generic download page?
> 
> isnt it suposed to redirect to generic flatpak download page?

I remembered that we have the same page for generic and optimized flatpak, so I can change button text

**Comment by ZhenyaGoroh** [comment]
> **Flatpak will install the Generic version!** Please select other formats if you want to install the Optimized version.
> 
> and the button will be **Download Generic anyway**

image
I used Download Generic, cuz with anyway the button is too wide

**Comment by NOCanoa** [comment]
Ye looks nice

**Pull request merged**
