### PR TITLE
fix: make Hero more centered

### PR DESCRIPTION
**Pull request by 27rogi**
The current Hero component has too much free space on bottom, I tried to fix it by using margin auto align and tweaked padding.

Before:
{CB48C2E7-08AA-4A3C-A8F6-19B4AEDFC58C}

After:
{4C7C319C-40C2-4C97-8FED-E469E852B235}

### CODE REVIEW

**Comment by NOCanoa** [comment]
conflict ._.

**Comment by KyleDL101** [comment]
@NOCanoa If this PR conflicts with mine, I'm happy to have mine closed and this one merged. It's 3 a.m. currently so I don't really see how my PR conflicts with this, but I'm willing to let this one be merged instead of mine. 

@27rogi Could I see what your PR looks like with the hero's "Beta out now" tag on mobile?

**Comment by 27rogi** [comment]
I was unable to test my fix because deployed version of the website did not include some other changes made to Hero which made it larger. I will commit once I merge every new change into my branch.

**Comment by 27rogi** [comment]
Okay, seems like Hero is not aligned correctly and my fix with margin-auto is not needed, but there is visible difference in padding for small and large screens, probably caused by image having transparent background corners.

I tried to compensate this difference.

Before:
{EA7457F8-0B36-4AA5-958D-D13FAEDED306}
{22FA734E-7699-4140-B925-0BCCAC62718F}

After:
{090D2ECF-92F3-4264-BA1D-A47DDAE07DA6}
{107340EA-D0F3-48B6-BBA0-141B17D46280}

**Comment by 27rogi** [comment]
Damn, something messed up with git. Will recreate PR based on latest changes.

**Pull request closed without merging**
