### PR TITLE
Improved the FAQ section

### PR DESCRIPTION
**Pull request by aashirwadRunjan**
Earlier the feature is default to open first item with corresponding images

Screenshot 2024-09-24 at 4 57 30 PM

Now I have made it to default close and when closed the corresponding image will be all three 

Screenshot 2024-09-24 at 4 57 27 PM

Since the images impact more than the text users if sees images first may tend to look into it.
Also an active dropdown looks a little unorganized for a new page.

Do let me know what you'll think

### CODE REVIEW

**Comment by aashirwadRunjan** [comment]
Now once a feature is clicked it functions like the regular one displaying the content of the Accordian.

**Comment by aashirwadRunjan** [comment]
Screenshot 2024-09-24 at 4 57 38 PM

**Comment by aashirwadRunjan** [comment]
have removed comments from the code to make it look clean.

**Comment by mauro-balades** [comment]
Thanks!

**Pull request merged**
