### PR TITLE
Brazilian Portuguese translation file added

### PR DESCRIPTION
**Pull request by mohvn**

### CODE REVIEW

**Comment by ktz-dev** [comment]
Hi. 

The ISO language code is pt-BR. 
Screenshot 2024-09-03 at 8 49 08 AM


So you need to name the json file **"pt-br.json"** (lower case only) then add `pt-BR` or `pt-br` to the `const SUPPORTED_LANGUAGES` list on line 4 of the `./src/i18n.ts` like this.

I wrote these instructions in the updated README-LANGUAGES.md for future contributors. 👍

**Comment by ktz-dev** [comment]
Oh actually, the language features were removed. I think the maintainers don't want to deal with the added complexity of it.

**Comment by ktz-dev** [comment]
I think they removed those language features. Maintainers probably didn't want the added complexity of everything being parameters.

**Comment by mohvn** [comment]
> I think they removed those language features. The translations were causing errors and outages 🫢.

yeah just noticed that, unfortunately 🫢

**Pull request closed without merging**
