### PR TITLE
Changed multiple themes files

### PR DESCRIPTION
**Pull request by Mailootje**
# Changed multiple theme files to redirect to /mods instead of /themes
- Renamed directory `src\app\themes` to `src\app\mods`
- Added new directory `src\app\themes` with a redirect to `../mods`

- Renamed file `src\lib\themes.ts` to `src\lib\mods.ts`
- Refactored some files that used the lib `@/lib/themes`

- Refactored multiple href's. 

Now we dont need to change anything in a desktop app.
This `Visit Store` link still works without problems:
image

### CODE REVIEW

**Comment by NOCanoa** [comment]
Ye looks like it but is the /theme/id -> /mods/id redirect work?

**Comment by Mailootje** [comment]
> Ye looks like it but is the /theme/id -> /mods/id redirect work?

Let me double check real quick

**Comment by NOCanoa** [comment]
> > Ye looks like it but is the /theme/id -> /mods/id redirect work?
> 
> Let me double check real quick

That cheff big thing old links should still work

**Comment by Mailootje** [comment]
> > > Ye looks like it but is the /theme/id -> /mods/id redirect work?
> > 
> > 
> > Let me double check real quick
> 
> That cheff big thing old links should still work

Exactly. Im gonna look into that right now

**Comment by NOCanoa** [comment]
> So it should be like this:
> `http://localhost:3000/themes/64cdc40f-2366-4b5b-8bad-d0524682595e`
> 
> Redirects to:
> `http://localhost:3000/mods/64cdc40f-2366-4b5b-8bad-d0524682595e`
> 
> 
> 

Yeah,

**Comment by Mailootje** [comment]
Alright that works now.

Added a new module.exports in the file `next.config.js`

**Comment by NOCanoa** [comment]
Because if somebody has a old link it should still go to that mod

**Comment by NOCanoa** [comment]
> Alright that works now.
> 
> Added a new module.exports in the file `next.config.js`

👀

**Comment by Mailootje** [comment]
> Because if somebody has a old link it should still go to that mod

Yeah if someone has the link:
`https://zen-browser.app/themes/bb61b145-6875-4afe-86f2-ab00024459dc`

They are getting redirected to the page:
`https://zen-browser.app/mods/bb61b145-6875-4afe-86f2-ab00024459dc`

**Comment by Mailootje** [comment]
image
Thats everything

**Comment by NOCanoa** [comment]
OK nice what did I say about #250 and this PR?

**Comment by Mailootje** [comment]
> OK nice what did I say about #250 and this PR?

Uh, well if his PR gets first pulled, i can just change the first line:
`import { getThemeAuthorLink, ZenTheme } from "@/lib/themes";`

**Comment by NOCanoa** [comment]
Let me get home 15min xP

**Comment by Mailootje** [comment]
So i have removed the exports in `next.config.js`
Added the [theme]\page.tsx again and redirected everything from `/themes/themeId` to `/mods/themeId`

https://github.com/zen-browser/www/pull/251/commits/b31d106f6d934c4c3bbbce39e25ca9279cf16fde

**Comment by Mailootje** [comment]
# Overview
- Renamed directory `src\app\themes` to `src\app\mods`
- Added new directory `src\app\themes` with a redirect to `../mods`

- Renamed file `src\lib\themes.ts` to `src\lib\mods.ts`
- Refactored some files that used the lib `@/lib/themes`

- Refactored multiple href's. 

- Requests from `/themes` are getting redirected to `/mods`
- Requests from `/themes/* (themeId)` getting redirected to `/mods/* (themeId)`

- Without changes in `next.config.js` so this is back to before without all the changes
-

**Comment by Mailootje** [comment]
Well it should be done now

**Comment by Mailootje** [comment]
It works as planned:
https://zen-browser-www.pages.dev/

**Pull request merged**
