### PR TITLE
fix: Add use-system-settings color mode and make it the default

### LINKED ISSUE #140: Follow system color scheme preference
The website is currently dark by default, with a toggle to switch between light/dark mode. Maybe it should be made to follow the system by default, using the [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media feature?

### PR DESCRIPTION
**Pull request by ktz-dev**
Fixes #140

The library we are using for dark/light mode (next-themes) reads the system preferences using the below css selector
``` css
[data-theme='dark'] {
    ... styles ...
}
```
but of course to get tailwind `dark:` prefix to work we needed to set dark mode based on className "dark"
``` css
.dark {
    ... styles ...
}
```

to fix this, just have both. 

``` css
[data-theme='dark'], .dark {
    ... styles ...
}
```

I also removed the `defaultTheme = dark` from the `<ThemeProvider />`so the default theme is whatever the system color scheme is set to. 

Note: If the user ever manually changes the theme themselves by clicking the navbar icon, the browser will save the theme they chose in localStorage and it won't use the system themes anymore. 

Screenshot 2024-08-31 at 11 56 31 AM

### CODE REVIEW

**Comment by ktz-dev** [comment]
Sorry, I'm stupid. I realised instead of making two code-blocks I could just have one code block with selector
``` css
[data-themes='dark'], .dark {

}
```

Fixed.

**Comment by bragefuglseth** [comment]
Ideally the button would have three states, but given that this is not a website people spend a whole lot of time on, I can see how that might not be worth the additional complexity.

**Comment by ktz-dev** [comment]
From a developer perspective that is simple but from a design perspective that is complex because the system-preference mode is the first mode that is set by default so you need an icon that communicates that the button is 'system-preference' but also that the button is the theme switcher. A moon and a sun are intuitively the theme switcher but what would be the system button.

**Comment by ktz-dev** [comment]
This is the developer perspective. You would change mode-toggle.tsx component from 

``` jsx
export function ModeToggle() {
  const { theme, setTheme } = useTheme();
  const toggleTheme = () => {
    setTheme(theme === "light" ? "dark" : "light");
  };
  return (
    <Button variant="ghost" size="icon" onClick={toggleTheme}>
      <SunIcon className="h-[1.2rem] w-[1.2rem] rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
      <MoonIcon className="absolute h-[1.2rem] w-[1.2rem] rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
      <span className="sr-only">Toggle theme</span>
    </Button>
  );
}
```

to 

``` js
export function ModeToggle() {
  const { theme, setTheme } = useTheme();
  const toggleTheme = () => {
    switch (theme) {
      case 'system':
        setTheme("dark");
        break;
      case 'dark':
        setTheme("light");
        break;
      case 'light':
        setTheme('system');
        break;
    }
  };
  let icon;
  switch (theme) {
    case 'system':
      icon = <GlobeIcon className="absolute h-[1.2rem] w-[1.2rem] rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />;
      break;
    case 'light':
      icon = <SunIcon className="h-[1.2rem] w-[1.2rem] rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />;
      break;
    case 'dark':
      icon = <MoonIcon className="absolute h-[1.2rem] w-[1.2rem] rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />;
      break;
  }
  return (
    <Button variant="ghost" size="icon" onClick={toggleTheme}>
      {icon}
      <span className="sr-only">Toggle theme</span>
    </Button>
  );
}
```

**Comment by ktz-dev** [comment]
Oh I got a hydration error. So instead of rendering them conditionally you would show them conditionally with ```
``` jsx
<GlobeIcon className={`${ (theme === 'system') ? 'visible' : 'hidden'`} ... the rest of the styles`} />
```
same idea but regardless, the issue is, if it was your first time on the page would a globe be intuitively the theme switcher?


https://github.com/user-attachments/assets/8aba377f-9f2b-4829-b3b5-e9d4910e2e42

**Comment by bragefuglseth** [comment]
Yeah, that's a tough one. Maybe a modified version "combining" the sun and the moon could work? I think the globe is more associated with switching languages.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg class="size-6" fill="none" stroke="currentColor" stroke-width="1.5" version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
 <path d="m11.095 12.884c1.7652 1.7707 4.2071 2.8663 6.9051 2.8663 1.33 0 2.597-0.266 3.752-0.748-1.5154 3.6327-5.0659 5.9983-9.002 5.998-2.7025 0-5.1481-1.0994-6.914-2.8753z" stroke-linecap="round" stroke-linejoin="round"/>
 <path d="m12 3v2.25m-6.364 0.386 1.591 1.591m-1.977 4.773h-2.25m17.935-8.9354-17.871 17.871m11.611-11.659c-0.62188-0.62162-1.5137-1.0265-2.6754-1.0265-3.79 0-4.7072 4.3093-2.7515 6.3949" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

follow-system

**Comment by ktz-dev** [comment]
Yeah I just deleted my entire rant about the whole thing and pushed it anyway. We use [Radix UI Icons](https://www.radix-ui.com/icons) and I don't see anything similar to that. I just used the globe icon.

**Comment by ktz-dev** [comment]
Oh what about this "Half 2" icon
Screenshot 2024-09-01 at 12 00 27 AM

**Comment by ktz-dev** [comment]
Oh yeah. That is very obviously a theme switcher in auto-mode. I think we have a winner.
Screenshot 2024-09-01 at 12 10 05 AM

**Comment by mauro-balades** [comment]
I liked MoonIcon, imma revert it to that

**Pull request merged**
