### PR TITLE
feat(lang): added ro.json

### PR DESCRIPTION
**Pull request by 8xu**

### CODE REVIEW

**Comment by ktz-dev** [comment]
Very nice, I'm glad you were able to add a language. You are the first.

Just a warning. 

That en.json I put was a placeholder. I'm trying to get the full en.json merged in this PR #138. If they merge it, it will break this romanian translation cause I changed the name of the variable. You'll see like this if it breaks:
Screenshot 2024-09-01 at 3 07 56 AM

See you'll see the name of the variables instead of the value. This makes it easy. It is telling you what you need to put in the ro.json to fix it. You need to put this:

```
{
    "navigation": {
        "navigation-getting-started": "Noțiuni de bază"
    }
}
```

To avoid having to manually find the broken text and add it to the json, just copy the entire contents of the en.json and translate the parts that matter and leave the rest in English.

**Comment by 8xu** [comment]
@ktz-dev this should do it 👍🏽

**Comment by 8xu** [comment]
@ktz-dev ummm... why did you delete that?

**Comment by ktz-dev** [comment]
I didn't want to complicate things 😅

**Pull request merged**
