### PR TITLE
feat: move "Toggle theme" to top-right

### PR DESCRIPTION
**Pull request by KyleDL101**
Moved "Toggle theme" to be in line with the nav bar and added theming.

### CODE REVIEW

**Comment by KyleDL101** [comment]
Sorry, forgot to sign this

**Comment by KyleDL101** [comment]
{E547CFAB-9270-4E9E-9A2B-6B80CFAA4E61}

looks like this

**Comment by KyleDL101** [comment]
Sorry. Have to merge with the upstream because I realise the navbar got pushed to the left from the "Toggle theme" button in my change. Next commit will fix that (which should be the final commit).

**Comment by KyleDL101** [comment]
{D81AD579-A71D-4E85-9CB8-7B67A3532157}

**Comment by KyleDL101** [comment]
Sorry this PR is a mess. Will do better PR formatting next time.

**Comment by NOCanoa** [comment]
Gona close this u can make a new one, kinda lost here

**Pull request closed without merging**
