### PR TITLE
Fixed #216

### LINKED ISSUE #216: OS selection interface blink
@Vigneshk5 You have fixed bug with os selection for os's that are not supported. But now when I open this page, I see this message that my os is not supported for a second and then it disappears. Could u fix it somehow?

image

### PR DESCRIPTION
**Pull request by ZhenyaGoroh**
@Vigneshk5 How's about this solution?

### CODE REVIEW

**Comment by Vigneshk5** [comment]
this solution is better, my solution 😅		
                if (userAgent.includes("Win")) {
			setSelectedPlatform("Windows");
		} else if (userAgent.includes("Mac")) {
			setSelectedPlatform("MacOS");
		} else if (userAgent.includes("Linux")) {
			setSelectedPlatform("Linux");
		} else {
			setSupported(false);
		}

**Comment by ZhenyaGoroh** [comment]
> this solution is better, my solution 😅 if (userAgent.includes("Win")) { setSelectedPlatform("Windows"); } else if (userAgent.includes("Mac")) { setSelectedPlatform("MacOS"); } else if (userAgent.includes("Linux")) { setSelectedPlatform("Linux"); } else { setSupported(false); }
> 
> ```
> 	{!supported && (
> 					<div className="mt-5 flex items-center">
> 						<InfoCircledIcon className="mr-2 size-4" />
> 						<p className="text-muted-foreground">
> 							Unfortunately, Zen Browser is not available for your platform at
> 							this time.
> 						</p>
> 					</div>
> 				)}
> ```

Your solution is good, but I don't really want to create one more state just to store 1 value which will be set only once when the component rendered.

**Comment by Vigneshk5** [comment]
yeah

**Comment by NOCanoa** [comment]
when this is ready to merge letme know

**Pull request merged**
