### PR TITLE
fix: changing logo svg color in a more effective way

### PR DESCRIPTION
**Pull request by mohvn**
This significantly reduces the load on the server, as all images are loaded only once when the component is assembled. Switching between logos happens entirely on the client, without additional requests.

### CODE REVIEW

**Comment by mohvn** [comment]
> still it send 12 req at first for all svg logos (Using the direct public folder for SVG icons was hitting the Vercel request limit) , which is why it was switched to an external CDN JS link.

however, the current approach still makes excessive requests every 2 seconds, leading to unnecessary bandwidth consumption. loading everything at once when the component mounts eliminates repeated requests, making it more efficient and reducing the load on server resources

**Comment by meetpateltech** [comment]
Yes, that's correct, but you should update the code based on the CDN link. Otherwise, at some point, the Vercel limit will still be reached.

**Comment by mohvn** [comment]
> Yes, that's correct, but you should update the code based on the CDN link. Otherwise, at some point, the Vercel limit will still be reached.

oh ok, I got it

**Comment by mauro-balades** [comment]
They are now CDNs, sorry

**Pull request closed without merging**
